default: &default
  adapter: postgresql
  host: <%= ENV['postgres_host'] %>
  port: <%= ENV['postgres_port'] %>
  database: <%= ENV['postgres_database'] %>
  username: <%= ENV['postgres_username'] %>
  password: <%= ENV['postgres_password'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
