development:
  secret_key_base: <%= ENV["secret_key_base"] %>
  secret_token: <%= ENV["secret_token"] %>

test:
  secret_key_base: <%= ENV["secret_key_base"] %>
  secret_token: <%= ENV["secret_token"] %>

staging:
  secret_key_base: <%= ENV["secret_key_base"] %>
  secret_token: <%= ENV["secret_token"] %>

production:
  secret_key_base: <%= ENV["secret_key_base"] %>
  secret_token: <%= ENV["secret_token"] %>

