---
:verbose: false
:concurrency: 2
:timeout: 30
:queues:
  - default
  - mailers

# SEE: https://github.com/mperham/sidekiq/blob/master/examples/config.yml
# SEE: https://github.com/brainopia/sidekiq-limit_fetch
